- id: insert-license
  name: insert-license-header-conda
  description: 'This pre-commit hook automatically inserts our license header at the beginning of source code files tracked by Git.'
  entry: insert-license --license-base64 Q29weXJpZ2h0IChjKSBRdWFudENvIHt5ZWFyX3N0YXJ0fS17eWVhcl9lbmR9ClNQRFgtTGljZW5zZS1JZGVudGlmaWVyOiBMaWNlbnNlUmVmLVF1YW50Q28K
  language: conda
  types: [python]
