name: Keep Repository Active
on:
  schedule:
    - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC

jobs:
  keep-alive: # Prevent cron jobs (in 'autoupdate.yml') from being suspended due to inactive repository
    name: Alive
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gautamkrishnar/keepalive-workflow@5b3128727d02fe1a892d0a2987517c9ec8ca7425
      with:
        commit_message: "Ah ah ah, stayin' alive"
        committer_username: ForrestQuant
        committer_email: "forrestquant@users.noreply.github.com"
        time_elapsed: 50  # days